# Generated by Django 4.2.2 on 2023-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_bay', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='zip',
            field=models.IntegerField(default=400000),
            preserve_default=False,
        ),
    ]
