# Generated by Django 4.2.6 on 2023-10-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_bay', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='payment_id',
            field=models.CharField(default='Cash on delivery.', max_length=100),
        ),
    ]
